server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://192.168.10.161:3306/mydemo
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ok
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 30
      min-idle: 5
      max-wait: 60000
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20



mybatis:
  type-aliases-package: com.njbdqn.mysee.vo
  mapper-locations: mapper/*.xml
pagehelper:
  helper-dialect: mysql